### ISSUE TITLE
Round-tripping dates with nanosecond precision adds digits?

### ISSUE THREAD

**Issue by achingbrain** [kawanet/timestamp-nano#3]
```js
const timestampNano = require("timestamp-nano")
const str = '2024-01-19T16:33:20.858209Z'
const date = timestampNano.fromString(str)

console.info('input ', str)
console.info('output', date.toString())
```

```console
$ node index.js
input  2024-01-19T16:33:20.858209Z
output 2024-01-19T16:33:20.858209000Z     <---- extra digits added
```

Is there a way to prevent this?

I have some signed binary data that contains a string representation of a timestamp.  When I round trip it from bytes to an object and back again, verifying the signature of the outputted data fails because the string that holds the time has changed due to the extra three `000`s added by calling `toString()` on the `Timestamp` returned by `timestampNano.fromString(...)`.

**Comment by kawanet** [comment]
@achingbrain thank you for the feedback.

The native Date class has milliseconds precision. It returns **3 digits** millisecond value with `toJSON()` method.

```
new Date().toJSON()
=> '2024-01-18T02:19:39.891Z'
```

`timestamp-nano` class has nano seconds precision, on the other hand. It returns **9 digits** nano second value with `toString()` method naturally, even if the value has milliseconds precision only.

```
Timestamp.fromDate(new Date()).toString()
=> '2024-01-18T02:19:39.891000000Z'
```

If you prefer to have **6 digits** micro second value like `.858209`,`timestamp-micro` module or something like that is the module you want.

If you prefer to remove trailing extra digits of `0`s, I've just got an idea to give an option argument to `toString(-1)` method.

- `toString(-1)` to remove trailing `0`s.
- `toString(0)` for second precision
- `toString(3)` for millisecond precision (3 digits fixed)
- `toString(6)` for micro second precision (6 digits fixed)
- `toString(9)` for nano second precision (9 digits fixed) - default behavior

However, in your case, it seems that you are not using the `toString()` method directly in your code. It'd need to have a global option parameter. I don't have a good design idea for that at this moment though.

**Comment by achingbrain** [comment]
I guess it's fair enough that `timestamp-nano` would convert a string to a nanosecond-precision timestamp.

Instead of passing numbers to `toString()` you could go all-in with a timestamp formatter similar to [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat)?

Not urgent though, I think this module is functioning as intended.

Thanks for your response.
